#!/usr/bin/env node

/**
 * LMS Hub — Split Lesson Files
 * 
 * Splits full lesson HTML files into:
 *   - Student version (Part A only) → lessons/Buoi_XX.html
 *   - Teacher version (full content) → lessons-teacher/Buoi_XX.html
 * 
 * The split point is the <h2> tag containing "PHẦN B" or "phan-b".
 * Everything before that tag is student content.
 * Everything from that tag onward is teacher-only content.
 * 
 * Usage:
 *   node core/scripts/split-lessons.js <course>
 *   node core/scripts/split-lessons.js ky-nang-ung-dung-ai
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const COURSES_DIR = join(ROOT, 'courses');

const courseName = process.argv[2];
if (!courseName) {
  console.error('Usage: node core/scripts/split-lessons.js <course>');
  process.exit(1);
}

const lessonsDir = join(COURSES_DIR, courseName, 'content', 'lessons');
const teacherDir = join(COURSES_DIR, courseName, 'content', 'lessons-teacher');

if (!existsSync(lessonsDir)) {
  console.error(`❌ Lessons directory not found: ${lessonsDir}`);
  process.exit(1);
}

// Create teacher directory
if (!existsSync(teacherDir)) {
  mkdirSync(teacherDir, { recursive: true });
}

const files = readdirSync(lessonsDir).filter(f => f.startsWith('Buoi_') && f.endsWith('.html'));

if (files.length === 0) {
  console.log('⚠️  No Buoi_XX.html files found in', lessonsDir);
  process.exit(0);
}

console.log(`\n📚 Splitting ${files.length} lesson files for "${courseName}"...\n`);

for (const file of files) {
  const fullPath = join(lessonsDir, file);
  const html = readFileSync(fullPath, 'utf-8');
  
  // Find the split point: <h2 ...>PHẦN B...</h2>
  // Match the <h2> tag that contains "phan-b" in its id
  const splitRegex = /<h2\s+id="phan-b[^"]*"[^>]*>/;
  const match = html.match(splitRegex);
  
  if (!match) {
    console.log(`  ⚠️  ${file} — No "PHẦN B" found, skipping (student-only content)`);
    continue;
  }
  
  const splitIndex = html.indexOf(match[0]);
  
  // Find the <hr /> that typically precedes PHẦN B
  // Look backwards from splitIndex for the nearest <hr
  const beforeSplit = html.substring(0, splitIndex);
  const lastHr = beforeSplit.lastIndexOf('<hr');
  const cutPoint = lastHr > 0 ? lastHr : splitIndex;
  
  // Student version: everything up to the cut point + closing tags
  const studentContent = html.substring(0, cutPoint);
  
  // We need to close the HTML properly for the student version
  // Find the closing </div> and </body></html> from the original
  const closingTags = `
        </div>
        <footer>
            Generated by Second Brain MD-to-Web Converter Skill
        </footer>
    </div>
</body>
</html>
`;
  
  // Also clean the TOC: remove all entries after Part A
  let studentHtml = studentContent;
  
  // Strategy: Find the closing </ul></li> of the Part A entry, 
  // then remove everything between that and the final TOC closing tags.
  // The Part A entry ends with </ul>\r\n</li> followed by teacher entries.
  
  // Find the end of Part A TOC entry: look for </ul> + </li> after #phan-a
  const partAEndPattern = /<li><a href="#phan-a[^"]*">[^<]*<\/a><ul>[\s\S]*?<\/ul>\s*<\/li>/;
  const partAMatch = studentHtml.match(partAEndPattern);
  
  if (partAMatch) {
    const partAEnd = studentHtml.indexOf(partAMatch[0]) + partAMatch[0].length;
    // Find the TOC closing: the next sequence of </ul></li> and </div>
    const tocClosePattern = /\s*(<\/ul>\s*<\/li>\s*)*<\/ul>\s*<\/div>/;
    const afterPartA = studentHtml.substring(partAEnd);
    const tocCloseMatch = afterPartA.match(tocClosePattern);
    
    if (tocCloseMatch) {
      // Remove everything between Part A end and TOC close
      const tocCloseStr = tocCloseMatch[0];
      // Keep only the closing tags, not the intermediate teacher TOC entries
      studentHtml = studentHtml.substring(0, partAEnd) + '\n</ul>\n</li>\n</ul>\n</div>' + afterPartA.substring(afterPartA.indexOf(tocCloseStr) + tocCloseStr.length);
    }
  }
  
  // Write student version (overwrite original)
  const studentFinal = studentHtml + closingTags;
  writeFileSync(fullPath, studentFinal, 'utf-8');
  
  // Write teacher version (full original) to teacher directory
  writeFileSync(join(teacherDir, file), html, 'utf-8');
  
  // Count approximate sizes
  const originalSize = Math.round(html.length / 1024);
  const studentSize = Math.round(studentFinal.length / 1024);
  const reduction = Math.round((1 - studentSize / originalSize) * 100);
  
  console.log(`  ✅ ${file}`);
  console.log(`     Student: ${studentSize}KB | Teacher: ${originalSize}KB | Reduced: ${reduction}%`);
}

console.log(`\n✨ Done! Student versions saved to: lessons/`);
console.log(`   Teacher versions saved to: lessons-teacher/`);
console.log(`\n📌 Note: Server serves lessons/ to students by default.`);
console.log(`   Teacher versions are accessible via /api/courses/sessions/:id/lesson-teacher (admin only).`);
